// ─── Question Database ────────────────────────────────────────────────────────

const database = {
    1: [
        { q: "A [BLANK] is a text-based interface that lets users interact with the OS by typing commands.", a: "shell" },
        { q: "A [BLANK] is an instruction that can only be executed in kernel mode, such as directly accessing I/O hardware.", a: "privileged instruction" },
        { q: "Moore's Law states that the number of transistors on a chip [BLANK] approximately every two years.", a: "doubles" },
        { q: "When a program calls save(), the CPU starts in [BLANK] mode, a [BLANK] triggers the switch to kernel mode, the [BLANK] accesses the disk, and the CPU returns to [BLANK] mode.", a: "user, system call, OS, user" },
        { q: "[BLANK] in operating systems means hiding hardware complexity behind a simpler, higher-level interface.", a: "abstraction" },
        { q: "The two CPU modes are [BLANK] mode (for applications) and [BLANK] mode (for the OS).", a: "user, kernel" },
        { q: "You [BLANK] have abstraction without virtualization, but you [BLANK] have virtualization without abstraction.", a: "can, cannot" },
        { q: "The CPU needs two modes so that user programs cannot directly execute [BLANK], protecting system integrity.", a: "privileged instructions" },
        { q: "[BLANK] keeps multiple programs in memory so the CPU stays busy while one process waits for I/O.", a: "multiprogramming" },
        { q: "[BLANK] extends multiprogramming by using a timer to switch the CPU between processes, giving each user a responsive experience.", a: "time-sharing" },
        { q: "The OS acts as a [BLANK] by allocating CPU time, memory, and I/O devices among competing processes.", a: "resource manager" },
        { q: "A [BLANK] is a service request from a user-mode program asking the kernel to perform a privileged operation.", a: "system call" },
        { q: "Time-sharing uses a hardware [BLANK] that fires at regular intervals to guarantee each process gets CPU time.", a: "timer" },
        { q: "A [BLANK] is triggered by an external device such as a keyboard, while a [BLANK] is triggered internally by a program event such as a divide-by-zero.", a: "interrupt, trap" },
        { q: "The switch from user mode to kernel mode is triggered by a [BLANK] (software) or an [BLANK] (hardware).", a: "trap, interrupt" },
        { q: "A shell runs in [BLANK] mode and must use [BLANK] to ask the kernel to access hardware on its behalf.", a: "user, system calls" },
        { q: "A compute-intensive program that never does I/O, under multiprogramming alone without time-sharing, could [BLANK] the CPU indefinitely.", a: "monopolize" },
        { q: "The 3 main roles of an OS are [BLANK], [BLANK], and [BLANK].", a: "extended machine, resource manager, security" },
        { q: "A divide-by-zero error is a [BLANK] because it is triggered by the running program, not an external device.", a: "trap" },
        { q: "A shell cannot directly access hardware because it runs in [BLANK] mode, which cannot execute privileged instructions.", a: "user" },
        { q: "[BLANK] solves the problem of CPU idle time caused by slow I/O operations by keeping multiple programs in memory.", a: "multiprogramming" },
        { q: "The OS is called an [BLANK] machine because it presents a richer, more convenient interface than the bare hardware.", a: "extended" },
        { q: "[BLANK] creates the illusion that each process has its own dedicated CPU and memory.", a: "virtualization" },
        { q: "Given p1 (compute=40, I/O=60) and p2 (compute=30, I/O=80) with a single I/O device and no multiprogramming, the job completes at time [BLANK].", a: "210" },
        { q: "Given p1 (compute=40, I/O=60) and p2 (compute=30, I/O=80) with a single I/O device and multiprogramming, the job completes at time [BLANK].", a: "180" },
        { q: "Given p1 (compute=40, I/O=60) and p2 (compute=30, I/O=80) with 2 I/O devices and no multiprogramming, the job completes at time [BLANK].", a: "210" },
        { q: "Given p1 (compute=40, I/O=60) and p2 (compute=30, I/O=80) with 2 I/O devices and multiprogramming, the job completes at time [BLANK].", a: "150" },
        { q: "The OS needs security and protection so that one [BLANK] cannot interfere with another's data or resources.", a: "process" },
        { q: "A [BLANK] OS handles thousands of users with job scheduling and high reliability, while a [BLANK] OS supports multiple users over a network providing shared services.", a: "mainframe, server" },
    ],
    2: [
        { q: "Threads within the same process share [BLANK], but each thread keeps its own private [BLANK].", a: "memory, stack" },
        { q: "A [BLANK] is the OS operation of saving the full state of one running process and restoring the saved state of another, allowing multiple processes to share the CPU.", a: "context switch" },
        { q: "From the CPU's perspective, multiprogramming solves the problem of CPU [BLANK] caused by processes waiting for slow I/O.", a: "idle time" },
        { q: "The CPU state stored in a process's PCB is 'current' only when the process is [BLANK]; otherwise it is out-of-date.", a: "running" },
        { q: "The [BLANK] (TCB) stores a thread's registers, stack pointer, program counter, and state.", a: "Thread Control Block" },
        { q: "The six states in the extended process state model are: [BLANK], [BLANK], [BLANK], [BLANK], [BLANK], and [BLANK].", a: "new, ready, running, blocked, suspended-ready, suspended-blocked" },
        { q: "A process in the Blocked state that receives the resource it was waiting for transitions to the [BLANK] state.", a: "ready" },
        { q: "A [BLANK] is a process that has finished execution but whose parent has not yet called wait(), so its exit status remains in the process table.", a: "zombie" },
        { q: "A Blocked process is waiting for [BLANK]; a Suspended process has been [BLANK] to disk to free memory.", a: "an event, swapped out" },
        { q: "A [BLANK] (PCB) is the OS data structure storing a process's PID, state, registers, memory map, and open file list.", a: "Process Control Block" },
        { q: "A [BLANK] (RCB) records a resource's type, status, and the list of processes waiting for it.", a: "Resource Control Block" },
        { q: "The three basic process states are [BLANK], [BLANK], and [BLANK].", a: "running, ready, blocked" },
        { q: "A process transitions from Running to Ready when the [BLANK] fires and the OS preempts it.", a: "timer" },
        { q: "A process transitions from Running to Blocked when it requests a [BLANK] that is not immediately available.", a: "resource" },
        { q: "A [BLANK] is a lightweight execution unit that shares the address space of its parent process, making it faster to create and switch between than full processes.", a: "thread" },
    ],
    3: [
        { q: "The [BLANK] list contains all processes ready to run but waiting for CPU time.", a: "ready" },
        { q: "[BLANK] scheduling decides which processes are admitted to memory from the job pool; [BLANK] scheduling decides which ready process runs next on the CPU.", a: "long-term, short-term" },
        { q: "A scheduling algorithm is [BLANK] if the OS can forcibly remove a running process from the CPU before it finishes its burst.", a: "preemptive" },
        { q: "[BLANK] scheduling always selects the process with the shortest estimated next CPU burst, provably minimizing average waiting time.", a: "SJF" },
        { q: "[BLANK] scheduling assigns each process a fixed time quantum and cycles through ready processes in order. It is preemptive.", a: "Round Robin" },
        { q: "[BLANK] time is the elapsed time from when a process enters the ready state until it first starts executing on the CPU.", a: "response" },
        { q: "[BLANK] in scheduling occurs when a process is perpetually denied CPU time because higher-priority or shorter processes keep arriving.", a: "starvation" },
        { q: "Turnaround time = [BLANK] minus [BLANK].", a: "completion time, arrival time" },
        { q: "The main practical problem with SJF is that the [BLANK] of the next CPU burst is not known in advance.", a: "length" },
        { q: "[BLANK] is the preemptive version of SJF: the running process is replaced when a new arrival has a shorter remaining burst.", a: "SRT" },
        { q: "[BLANK] scheduling serves processes in arrival order, is non-preemptive, and can cause the convoy effect.", a: "FIFO" },
        { q: "For P1(burst=8), P2(burst=3), P3(burst=5) all arriving at t=0, SJF average waiting time = [BLANK].", a: "3.67" },
        { q: "For P1(burst=4, t=0), P2(burst=2, t=1), P3(burst=3, t=2) with FIFO, average turnaround time = [BLANK].", a: "5.33" },
        { q: "For P1(burst=7) and P2(burst=4) both at t=0 with RR quantum=3, average turnaround time = [BLANK].", a: "10.5" },
        { q: "In a multilevel feedback queue, [BLANK]-bound processes get higher priority because they voluntarily yield the CPU before their quantum expires.", a: "I/O" },
        { q: "In a non-preemptive scheduling algorithm, the scheduler makes a decision only when the current process [BLANK] or terminates.", a: "blocks" },
        { q: "Multilevel queues are used instead of a single scheduling algorithm because different types of processes (e.g., interactive vs. batch) have [BLANK] scheduling needs.", a: "different" },
    ],
    4: [
        { q: "The four requirements for any critical section solution are: [BLANK], [BLANK], [BLANK], and [BLANK].", a: "mutual exclusion, progress, bounded waiting, performance" },
        { q: "In monitor implementation, each condition variable c requires a corresponding [BLANK] (initialized to 0) to allow processes to block on that condition.", a: "semaphore" },
        { q: "When the producer and consumer run at approximately the same speed, the bounded buffer should use a [BLANK] number of slots.", a: "small" },
        { q: "The semaphore 'mutex' should be initialized to [BLANK] because it allows exactly one process at a time into the critical section.", a: "1" },
        { q: "A [BLANK] is a high-level synchronization construct that bundles shared data with procedures and automatically enforces mutual exclusion on all procedure calls.", a: "monitor" },
        { q: "After a producer fills 100 slots and a consumer empties 90, the value of the semaphore 'full' = [BLANK].", a: "10" },
        { q: "The c.[BLANK] operation on a condition variable blocks the calling process; c.[BLANK] wakes one waiting process.", a: "wait, signal" },
        { q: "A [BLANK] condition occurs when two or more processes access shared data concurrently and the result depends on the timing of execution.", a: "race" },
        { q: "In the bounded buffer monitor, the producer [BLANK] when the buffer is full.", a: "waits" },
        { q: "The P(s) operation: if s > 0, it [BLANK] s by 1; if s = 0, the calling process is [BLANK].", a: "decrements, blocked" },
        { q: "A semaphore is a [BLANK] integer variable accessed only through the atomic P and V operations.", a: "non-negative" },
        { q: "In the bounded buffer problem, when next_in equals next_out the buffer is [BLANK].", a: "empty" },
        { q: "In the alarm_clock monitor, the function [BLANK] increments the 'now' variable and signals waiting processes.", a: "tick" },
        { q: "Incorrect interleaving of 'x = x + 1' and 'x = x + 2' starting with x = 0 can produce x = [BLANK] instead of the correct value of 3.", a: "2" },
        { q: "The critical section problem protects [BLANK] access to shared data; the producer-consumer problem synchronizes [BLANK] processes.", a: "concurrent, cooperating" },
        { q: "The [BLANK] operation on a semaphore increments s by 1, and if any processes are waiting, one is unblocked.", a: "V" },
        { q: "In the bounded buffer problem, before placing data into the buffer, the producer must wait for [BLANK] and [BLANK].", a: "empty, mutex" },
    ],
    5: [
        { q: "In the alarm_clock monitor, the function [BLANK] increments the 'now' variable and signals waiting processes.", a: "tick" },
        { q: "Continuous deadlock detection should trigger the reduction algorithm only when the current operation is a [BLANK] and the requesting process becomes [BLANK].", a: "request, blocked" },
        { q: "A [BLANK] resource can be requested, acquired, and later released; a [BLANK] resource is created by one process and consumed by another.", a: "reusable, consumable" },
        { q: "In the Banker's Algorithm, if granting a request produces a state that is not completely reducible, the request is [BLANK].", a: "denied" },
        { q: "In the Banker's Algorithm, 'Potential Requests' = [BLANK] minus [BLANK].", a: "maximum claim, current allocation" },
        { q: "The two conditions that must BOTH hold for deadlock to occur with reusable resources are [BLANK] and [BLANK].", a: "circular wait, no preemption" },
        { q: "The Banker's Algorithm is named after how banks issue [BLANK]; a process's maximum claim corresponds to a customer's [BLANK] limit.", a: "loans, credit" },
        { q: "In a resource allocation graph, processes are represented by [BLANK] and resources are represented by [BLANK].", a: "circles, squares" },
        { q: "An edge directed from a resource to a process represents a resource [BLANK]; an edge from a process to a resource represents a resource [BLANK].", a: "assignment, request" },
        { q: "A resource allocation graph is completely [BLANK] if the reduction algorithm successfully removes all processes from the graph.", a: "reducible" },
        { q: "A process is [BLANK] on a resource if it has outstanding request edges but the resource lacks enough free units to satisfy the request.", a: "blocked" },
        { q: "In a wait-for graph (single-unit resources only), a directed [BLANK] is a necessary and sufficient condition for deadlock.", a: "cycle" },
        { q: "In the wait-for graph with edges p1→p2, p2→p3, p3→p4, p4→p2, p5→p4, the processes forming the deadlock cycle are [BLANK].", a: "p2, p3, p4" },
        { q: "A resource r has 3 units. p1 holds 1 unit, p2 holds 2 units, and p1 requests 2 more. p1 is [BLANK] because there are 0 free units.", a: "blocked" },
    ],
    6: [
        { q: "The practical advantage of dynamic relocation over static relocation is that programs can be [BLANK] in memory at runtime without recompilation.", a: "relocated" },
        { q: "The [BLANK] allocation strategy scans holes from the start and picks the first one large enough; the [BLANK] strategy scans from where the last allocation ended.", a: "first fit, next fit" },
        { q: "The [BLANK] allocation strategy selects the smallest hole large enough for a request; [BLANK] always selects the largest available hole.", a: "best fit, worst fit" },
        { q: "In a paged system, the higher-order bits of a logical address represent the [BLANK] number, and the lower-order bits represent the [BLANK] within that page.", a: "page, offset" },
        { q: "A [BLANK] address identifies a memory location in an abstraction of physical memory, allowing programs to be written without knowing their final load address.", a: "logical" },
        { q: "With dynamic linking, if a shared function is never called during execution, [BLANK] copies of it are loaded into memory.", a: "0" },
        { q: "Unlike a fixed-size page, a [BLANK] is a variable-size block of a logical address space. Each process has a [BLANK] table recording each one's base address and size.", a: "segment, segment" },
        { q: "The TLB uses the [BLANK] of locality principle to decide which entry to evict when full, typically removing the least recently used entry.", a: "temporal" },
        { q: "Coalescing solves [BLANK] fragmentation by merging adjacent free memory holes into one larger hole after a block is freed.", a: "external" },
        { q: "In a paged memory system: a fixed-size block of logical address space is a [BLANK]; a fixed-size block of physical memory is a [BLANK]; the data structure mapping one to the other is a [BLANK].", a: "page, frame, page table" },
        { q: "Paging eliminates [BLANK] fragmentation but introduces [BLANK] fragmentation, because a process's size is rarely an exact multiple of the page size.", a: "external, internal" },
        { q: "A [BLANK] (TLB) is a fast associative memory buffer in the CPU that caches recent logical-to-physical address translations.", a: "translation lookaside buffer" },
        { q: "With [BLANK] relocation, all logical addresses are converted to physical addresses before execution. With [BLANK] relocation, conversion happens at runtime for each memory reference.", a: "static, dynamic" },
        { q: "In a system using both segmentation and paging without a TLB, accessing a single logical address requires [BLANK] main memory accesses (segment table, page table, and actual data).", a: "3" },
        { q: "A [BLANK] register holds the physical starting address of a program in memory and is added by the CPU to every logical address at runtime.", a: "base" },
        { q: "With [BLANK] linking, a library function is loaded only when first called at runtime. With [BLANK] linking, all functions are combined into the executable before execution.", a: "dynamic, static" },
        { q: "When adjacent holes are combined into one larger hole after a block is released, this process is called [BLANK].", a: "coalescing" },
        { q: "A [BLANK] is a fixed-size unit of data, typically 1, 2, or 4 bytes, that makes up the basic addressable element of physical memory.", a: "word" },
    ],
    7: [
        { q: "In the second chance (clock) algorithm, when the clock hand reaches a page with reference bit = 1, the bit is cleared to [BLANK] and the page is skipped, giving it a second chance", a: "0" },
        { q: "Load control is the activity of determining how many processes should be running [BLANK] at any given time to maximize overall system performance.", a: "concurrently" },
        { q: "Immediately after a page is loaded into memory following a page fault, the present bit is set to [BLANK] and the modified bit is set to [BLANK].", a: "1, 0" },
        { q: "A [BLANK] is the sequence of page numbers referenced by an executing program during a given time interval, used to compare page replacement algorithms.", a: "reference string" },
        { q: "A limitation of the aging algorithm is that two pages accessed within the same [BLANK] appear identical in their register values, making them indistinguishable for replacement purposes.", a: "clock interval" },
        { q: "In the second chance algorithm, a page is evicted only when the clock hand finds its reference bit equal to [BLANK].", a: "0" },
        { q: "The [BLANK] page replacement algorithm selects the page that will not be referenced for the longest time in the future, guaranteeing the fewest possible page faults.", a: "optimal" },
        { q: "The [BLANK] page replacement algorithm selects the page that has not been referenced for the longest time.", a: "LRU" },
        { q: "In the effective access time formula E = (1 - P) x m + P x S, the variable S represents the [BLANK].", a: "service time" },
        { q: "A large page table can be subdivided into pages managed by a higher order [BLANK] to reduce the amount of table that must be kept in RAM.", a: "directory" },
        { q: "Two processes share a function f. With dynamic linking, if neither process ever calls f during a run, how many copies of f are loaded into memory? [BLANK]", a: "0" },
        { q: "At each memory reference, the working set algorithm evicts all pages that are [BLANK] the current window of size d.", a: "outside" },
        { q: "The optimal algorithm is not realizable in practice because replacement decisions depend on [BLANK], which are unknown at runtime.", a: "future references" },
        { q: "Demand paging loads a page into memory only when [BLANK], rather than at the start of execution.", a: "needed" },
        { q: "With a paged page table, the page number p is split into two components p1 and p2, where p1 selects an entry in [BLANK], which points to one page of the page table.", a: "page directory" },
        { q: "The working set W(t, d) of a process is the set of distinct pages referenced during the past [BLANK] memory operations preceding time t.", a: "d" },
        { q: "In the 7-step page fault handling sequence, what must the OS do before resuming the process after a page fault? List the key steps in order. [BLANK]", a: "update page table" },
        { q: "A [BLANK] register holds the physical starting address of a program in memory and is added by the CPU to every logical address at runtime to produce the correct physical address.", a: "base" },
        { q: "The [BLANK] page replacement algorithm selects the page that has been resident in memory for the longest time", a: "FIFO" },
        { q: "The L = S criterion states that CPU utilization is near maximum when L, the mean time [BLANK], equals S, the time needed to service one page fault.", a: "between page faults" },
        { q: "Bélády's anomaly can occur with [BLANK] page replacement, but does NOT occur with LRU or Optimal", a: "FIFO" },
        { q: "The aging page replacement algorithm uses an [BLANK] that is shifted right at each clock tick and loaded with the page's reference bit to approximate how recently the page was used", a: "aging register" },
        { q: "When m = 1, a page must be [BLANK] to disk before its frame can be reused for another page", a: "written" },
        { q: "When L < S, the OS must [BLANK] the number of concurrent processes to avoid thrashing.", a: "decrease" },
        { q: "As page size increases, the memory space covered by the TLB [BLANK] because each TLB entry maps a larger region.", a: "increases" },
        { q: "The page fault frequency algorithm adjusts the resident set based on the [BLANK] between consecutive page faults", a: "time" },
        { q: "The [BLANK] bit is a binary flag in each page table entry that indicates whether the corresponding page has been modified during execution.", a: "modified" },
        { q: "Thrashing is an execution state in which most of the time is spent moving between [BLANK] and [BLANK] while the CPU is mostly idle.", a: "memory and disk" },
        { q: "A [BLANK] is an interrupt that occurs when a program attempts to reference a non-resident page, causing the OS to load the page from the disk.", a: "page fault" },
        { q: "Under the working set page placement algorithm, a process is only allowed to run if enough frames are available to hold its complete [BLANK].", a: "working set" },
        { q: "Under the PFF algorithm, when the time since the last page fault is less than or equal to T, the faulting page is added to the resident set and the resident set [BLANK].", a: "grows" },
        { q: "When the present bit p = 0, any attempt to access that page triggers a [BLANK]", a: "page fault" },
        { q: "In the aging algorithm, the page chosen for replacement is the one with the [BLANK] register value, indicating it has been used least recently.", a: "smallest" },
        { q: "Effective access time is calculated as E = [BLANK]", a: "(1-P)*m + P*S" },
        { q: "In the effective access time formula E = (1 - P) x m + P x S, the variable P represents the [BLANK]", a: "page fault rate" },
        { q: "When m = 0, page is considered [BLANK] and can be overwritten during replacement without writing it back to disk.", a: "clean" },
    ],
    8: [
        { q: "The [BLANK] is a data structure kept in main memory that tracks all files currently in use. It facilitates efficient access to and manipulation of open files, storing information such as the current position, file length, and a pointer to the file's attribute structure.", a: "open file table" },
        { q: "The main drawback of storing all file attributes inside each directory entry is that file directories can become very large, which slows down searches. An alternative is to store only the file name in the directory and use a pointer to a separate [BLANK] that holds all the file's attributes.", a: "file control block" },
        { q: "A [BLANK] is a path that begins from the current working directory and rather than from the top of the hierarchy, allowing shorter path references for files in or near the current directory.", a: "relative path" },
        { q: "A [BLANK] is a data structure used for free space management where each bit represents one disk block. A value of 1 indicates the block is [BLANK], and a value of 0 indicates the block is [BLANK].", a: "bitmap, free, allocated" },
        { q: "A [BLANK] is a structure of related data items — possibly of different data types — identified within a file by a numeric identifier or a unique key field.", a: "record" },
        { q: "In a directed acyclic directory hierarchy, a [BLANK] is a non-negative integer associated with a file that indicates how many directories are currently pointing to it. A file is physically deleted only when this value reaches 0.", a: "link count" },
        { q: "A [BLANK] is a short sequence of characters at the start of the file header that identifies the file type allowing the OS to determine which programs are permitted to access and interpret the file.", a: "magic number" },
        { q: "In a tree structured directory hierarchy, the notation [BLANK] is used to refer to the parent of the current directory, allowing navigation upward in the hierarchy.", a: ".." },
        { q: "A [BLANK] is an integral part of every OS whose function is to implement the concept of files, managing data on secondary storage and providing a high level interface to users.", a: "file system" },
        { q: "Given a current file position k, and a block size b, the block number containing position k is computed as [BLANK], and the offset within that block is computed as [BLANK].", a: "k/b, k mod b" },
        { q: "Under the PFF algorithm, when the time since the last page fault exceeds T, pages not referenced since the last page fault are [BLANK] from the resident set.", a: "removed" },
        { q: "To allocate a disk block using a bitmap when individual bits cannot be addressed directly, a bitwise logical [BLANK] operation is applied to the byte containing the target bit, using a mask with a 1 in the corresponding position.", a: "AND" },
        { q: "A [BLANK] is a data structure associated with a filename that contains all relevant attributes of the file. In Unix, this structure is called an [BLANK].", a: "file control block, i-node" },
        { q: "In the block allocation scheme used by Unix, the file control block stores the block numbers of the first n file blocks directly. If a file requires more than n blocks, the next entry in the file control block points to a [BLANK], which stores additional block numbers.", a: "single indirect block" },
        { q: "The most common file access method is [BLANK]. In this method, the OS maintains the current position within the file, and each read/write operation accesses the next n bytes or the next record.", a: "sequential access" },
        { q: "During a read operation, the file system avoids reading an entire disk block for every call, maintaining a [BLANK] in the OFT entry. Data is copied from this structure to memory, and a new disk block is loaded only when the end of it is reached.", a: "read/write buffer" },
        { q: "The close file operation reverses the effects of the open operation. If the r/w buffer was modified, it saves the buffer to disk, updates the [BLANK] in the FCB and then frees the OFT entry.", a: "file length" },
        { q: "An [BLANK] is a path that uniquely identifies a file by listing all directory and file names from the top of the hierarchy down to the target file, with names separated by a delimiter such as a forward slash", a: "absolute path name" },
        { q: "In a [BLANK] block allocation scheme, file blocks may be scattered across the disk the FCB points to the first block, and each block contains a pointer to the next block.", a: "linked" },
        { q: "A [BLANK] is a named collection of information managed on secondary storage by the operating system, which a user can access using high-level operations without knowing the specific characteristics of the underlying device.", a: "file" },
        { q: "When a file is opened, the open operation returns a(n) [BLANK] into the open file table to the calling process, which is used for all subsequent read, write, and seek operations on the file.", a: "index" },
        { q: "To allocate a free disk block using a bitmap when individual bits cannot be addressed directly, a bitwise logical [BLANK] operation is applied to the byte containing the target bit, using a mask with a 0 in the corresponding position.", a: "AND" },
        { q: "A [BLANK] is an array where each entry corresponds to one disk block. A file's blocks are chained together by links within this array. When it is cached in memory, both sequential and direct access become efficient since no seek operations are needed to follow the chain.", a: "File Allocation Table" },
        { q: "When a file is destroyed, the file system frees the file's [BLANK] and directory entry. If the file is not empty, the disk blocks holding its contents are also marked as free.", a: "FCB" },
        { q: "[BLANK] is information about the format and organization of a file's data. It is generally stored in a file header and is visible only to the file system itself, not to the file's user.", a: "Metadata" },
        { q: "When the open operation is called, it copies a pointer to the [BLANK] into the OFT entry so that the file directory does not need to be searched again on future accesses.", a: "FCB" },
        { q: "In a [BLANK] block allocation scheme, every file is mapped to an unbroken sequence of disk blocks. The FCB stores only the first disk block and the file length. A major drawback is that a file cannot be expanded if the block immediately following the file is occupied.", a: "contiguous" },
        { q: "To allocate a disk block using a bitmap when individual bits cannot be addressed directly, a bitwise logical [BLANK] operation is applied to the byte containing the target bit, using a mask with a 1 in the corresponding position.", a: "OR" },
        { q: "A [BLANK] is a directory entry that points to a file or directory like a regular entry but is treated differently during deletion: deleting it removes only the entry itself, not the file it points to.", a: "symbolic link" },
        { q: "In an [BLANK] block allocation scheme, each file has a dedicated table that records the disk block numbers belonging to the file. This scheme supports both fast sequential and direct access but requires deciding in advance how large the table should be.", a: "indexed" },
    ],
    9: [
        { q: "In a [BLANK] block allocation scheme, file blocks may be scattered across the disk. The FCB points to the first block, and each block contains a pointer to the next block. A key drawback is that direct access to a specific block is not possible without reading all preceding blocks.", a: "linked" },
        { q: "A [BLANK] is an electronic circuit capable of operating a specific I/O device using binary signals, and its interface consists of a set of hardware registers and flags.", a: "device controller" },
        { q: "The [BLANK] scheduling algorithm always selects the pending disk request that requires the shortest travel distance from the current head position, maximizing performance but risking starvation of distant tracks.", a: "SSTF" },
        { q: "The [BLANK] scheduling algorithm (also called the elevator algorithm) services disk requests sequentially in the current direction of travel, reversing direction only when the outermost pending request is reached.", a: "SCAN" },
        { q: "A [BLANK] is a register or an area of main memory used to hold data produced by one process of device so it can be consumed later by another processor device, thereby decoupling the producer and consumer in time.", a: "buffer" },
        { q: "[BLANK] is a style of I/O programming where the CPU, running the device driver, is responsible for copying all data between the I/O device controller and main memory.", a: "programmed i/o" },
        { q: "The [BLANK] scheduling algorithm is a variant of Scan that services requests in only one direction; when the last request in that direction is reached, the head sweeps back to the other end without servicing any requests.", a: "C-SCAN" },
        { q: "Unlike Scan, C-Scan guarantees a [BLANK] access time to all tracks because the head always services requests in the same direction, giving no positional advantage to midrange tracks.", a: "fairer" },
        { q: "A disk [BLANK] (also called a buffer cache) is an area of main memory used to cache recently accessed disk blocks, reducing the number of physical disk accesses required.", a: "buffer cache" },
        { q: "With [BLANK] forwarding, a damaged disk block is mapped directly to a spare sector, which is fast and simple but causes logical blocks to no longer map to consecutive sectors.", a: "sector" },
        { q: "In [BLANK] input mode, the keyboard driver preprocesses characters as the user types – handling backspaces and special keys — before passing the completed line to the application.", a: "cooked" },
        { q: "In a RAID with [BLANK] parity, the redundant parity blocks are spread across all disks rather than stored on one dedicated disk, balancing the load of computing and checking parity information.", a: "distributed" },
        { q: "A [BLANK] controller is a hardware component that allows devices to transfer data directly to and from main memory without requiring the CPU to copy the data.", a: "DMA" },
        { q: "A [BLANK] (ECC) includes multiple parity bits in a data string to permit not only the detection but also the automatic correction of some number of erroneous bits.", a: "error-correcting code" },
        { q: "In Hamming code, a single-bit error can be identified by [BLANK] the positions of all parity bits that are found to be incorrect after reading the encoded string.", a: "summing" },
        { q: "A disk surface is organized into concentric [BLANK], each of which is divided into a fixed number of sectors.", a: "tracks" },
        { q: "When interrupts are used for I/O, after starting the operation the driver [BLANK] itself instead of repeatedly polling the busy flag, freeing the CPU to serve other processes.", a: "blocks" },
        { q: "The controller register that the CPU writes to in order to start an I/O operation — for example, specifying 'read' or 'write' — is the [BLANK] register", a: "command" },
        { q: "The [BLANK] code is a popular ECC that corrects a single bit error by inserting even-parity bits at positions 1, 2, 4, 8, … in the encoded string.", a: "Hamming" },
        { q: "[BLANK] is a technique where the CPU determines whether a device is busy or idle by repeatedly reading a flag that is set and reset by the device controller.", a: "polling" },
        { q: "The [BLANK] transfer rate is the rate at which data is streamed to or from the disk once the read/write head is positioned at the beginning of the desired sector.", a: "sustained" },
        { q: "A major drawback of SSTF disk scheduling is that requests for tracks far from the current head position may be postponed indefinitely — a condition known as [BLANK].", a: "starvation" },
        { q: "RAID [BLANK] provides no redundant information and uses only striping to improve access speed, meaning a media failure on any disk results in the loss of that block's data.", a: "0" },
        { q: "A [BLANK] is a device-specific program that implements I/O operations by interacting with the device controller, and is typically supplied by the device manufacturer", a: "device driver" },
        { q: "RAID [BLANK] provides full redundancy by maintaining a complete duplicate copy of all data on a separate set of disks, using a stable storage protocol to prevent data loss.", a: "1" },
        { q: "[BLANK] is a technique where a sequence of data blocks b[i] is distributed over n disks such that disk[i] contains block b[i] modulo n, allowing multiple blocks to be accessed concurrently", a: "striping" },
        { q: "The controller register that is set by the controller after an operation completes to indicate whether the operation succeeded or failed is the [BLANK] register.", a: "status" },
        { q: "The controller register that is set by the controller to indicate whether the device is currently busy or idle is the [BLANK] register.", a: "busy" },
        { q: "The [BLANK] data rate accounts for seek times and other overhead and represents the rate at which the disk can transfer data continuously over time across multiple accesses.", a: "average" },
        { q: "A stable [BLANK] guarantees that every block is updated atomically — after the operation, the block contains either the old or the new value, but never a partially updated value.", a: "storage" },
        { q: "To allow new devices to be added without modifying the OS, the I/O system supports a small set of generic [BLANK] instructions that every new driver must implement.", a: "interface" },
        { q: "The [BLANK] time is the time required to move the read/write head from its current track to the track containing the desired sector.", a: "seek" },
    ],
    10: [
        { q: "With sector [BLANK], all blocks following a damaged block are shifted one position to the right so that the logical blocks remain mapped to consecutive sectors, at the cost of more initial work.", a: "slipping" },
        { q: "A logic bomb differs from other malware in that its destructive payload only executes when a specific [BLANK] is met, such as a date or the deletion of an employee record.", a: "condition" },
        { q: "A piece of executable code that inserts itself into legitimate programs and replicates to other programs and systems with the intention of causing harm is called a [BLANK].", a: "virus" },
        { q: "In challenge-response authentication, the server sends a different random number with each login attempt, which prevents an attacker from reusing an intercepted response in a [BLANK] attack.", a: "replay" },
        { q: "User authentication methods that measure and analyze unique physical or behavioral characteristics of a person, such as fingerprints or retina patterns are collectively known as [BLANK].", a: "biometrics" },
        { q: "[BLANK] cryptography (also called symmetric cryptography) uses the same key for both encryption and decryption, while public key cryptography uses two different keys.", a: "secret key" },
        { q: "In [BLANK] authentication the system sends the user a random number r, the user computes H(r,pw) using a one-way hash function and returns the result and the system verifies it by computing the same function independently.", a: "zero-knowledge" },
        { q: "The RSA public key cryptosystem is considered computationally secure because breaking it requires [BLANK] the modulus n, which is the product of two very large prime numbers — a task that is computationally infeasible.", a: "factoring" },
        { q: "A sandbox protects a system by confining an imported program so that it cannot access memory [BLANK] its designated region, regardless of what the program attempts to do.", a: "outside" },
        { q: "Unauthorized code that is secretly inserted into a system and executes at a specified time to perform a destructive action, often used for blackmail or revenge is called a [BLANK].", a: "logic bomb" },
        { q: "A mechanism embedded by a programmer that bypasses normal user authentication and allows unauthorized access to the system at a later time is called a [BLANK] (also known as a trapdoor).", a: "back door" },
        { q: "An unauthorized program that exploits one or more system vulnerabilities to spawn copies of itself across other systems via a network is called a [BLANK].", a: "worm" },
        { q: "The disclosure of confidential or secret information by a legitimate user to an unauthorized party is known as [BLANK].", a: "leakage" },
        { q: "Lowering the threshold in a biometric system reduces the number of genuine users who are incorrectly rejected, but increases the number of [BLANK] attempts that are incorrectly accepted.", a: "imposter" },
        { q: "A back door is especially dangerous because it allows an attacker to gain access to a system while bypassing normal [BLANK].", a: "authentication" },
        { q: "In biometric authentication, when the probability distribution of genuine and imposter attempts overlap, a [BLANK] value must be chosen that balances the rate of rejected genuine attempts against the rate of accepted imposter attempts.", a: "threshold" },
        { q: "A [BLANK] is associated with each domain and contains entries of the form (objects, rights). Possession of an entry in this list serves as authorization — similar to holding a ticket — to perform the listed operations on the object.", a: "capability list" },
        { q: "A buffer overflow attack is possible because the vulnerable program fails to check the [BLANK] of user input before writing it to a fixed-size buffer on the stack.", a: "length" },
        { q: "An [BLANK] is associated with each object and contains entries of the form (domain, rights), listing every domain that has any access to that object along with what operations are permitted.", a: "access control list" },
        { q: "The main drawback of capability lists compared to access lists is the difficulty of [BLANK] a right, because capabilities for a given object are scattered across the individual lists of many different processes rather than stored in one place.", a: "revoking" },
        { q: "The [BLANK] right, when attached to another right r, indicates that the holder of r is permitted to copy it to another domain. Without it, the right cannot be propagated.", a: "copy" },
        { q: "When a legitimate user runs a program that displays a fake copy of the login screen in order to steal credentials from an unsuspecting user, the attack is called [BLANK].", a: "phishing" },
        { q: "An intrusion technique that exploits a program's failure to check the size of user input, allowing an attacker to overwrite the return address on the stack and transfer control to arbitrary code is called a [BLANK].", a: "buffer overflow" },
        { q: "A function that converts a variable-length input string into a fixed-length output string in a way that cannot be mathematically reversed is called a [BLANK].", a: "one-way hash function" },
        { q: "Unlike a virus, a worm does not need to [BLANK] itself into an existing host program in order to spread to other systems.", a: "insert" },
        { q: "A virus that uses encryption to change its appearance with each new infection is trying to evade [BLANK]-based antivirus detection.", a: "signature" },
        { q: "A program that appears to provide a useful service to the user but secretly contains a hidden function intended to violate computer security is called a [BLANK].", a: "trojan horse" },
        { q: "[BLANK] storage uses two independent disks containing identical copies of all data, along with a strict read/write/recovery protocol, to guarantee data consistency.", a: "stable" },
    ],
    11: [
        { q: "A collection of computers interconnected by a network into one coherent system is called a [BLANK].", a: "distributed system" },
        { q: "The individual nodes of a distributed system's network are called [BLANK].", a: "hosts" },
        { q: "In a distributed system, processes communicate by sending [BLANK].", a: "messages" },
        { q: "A unique network address assigned to each host to allow message routing is called an [BLANK].", a: "IP address" },
        { q: "A [BLANK] network, also called a LAN, has fast links and a limited geographic extent.", a: "local area" },
        { q: "A [BLANK] network, also called a WAN, has slow links and a wide geographic extent.", a: "wide area" },
        { q: "OS extensions can join local memories of LAN hosts into a common shared address space called [BLANK].", a: "distributed shared memory" },
        { q: "Multiple disjoint file systems in a WAN can be federated into a single shared system called a [BLANK].", a: "distributed file system" },
        { q: "The process of mapping a symbolic host name to its IP address is called [BLANK].", a: "name resolution" },
        { q: "The best-known system for hierarchical name resolution on the Internet is the [BLANK].", a: "DNS" },
        { q: "In DNS, all hosts are arranged in a tree where each subtree is called a [BLANK].", a: "domain" },
        { q: "The root level of the DNS tree contains the most general names such as [BLANK].", a: "top-level domains" },
        { q: "A host responsible for some portion of the DNS name space is called a [BLANK].", a: "name server" },
        { q: "A process that resolves path names from an application by querying name servers is called a [BLANK].", a: "resolver" },
        { q: "A DNS query that involves only one name server, which returns the IP of the next lower server, is called [BLANK].", a: "iterative" },
        { q: "A DNS query that propagates down through lower-level servers until the final IP is found is called [BLANK].", a: "recursive" },
        { q: "To reduce queries sent to name servers, each resolver maintains a [BLANK] of recently resolved names.", a: "cache" },
        { q: "When a portion of a future query matches a cached entry, the resolver sends only the [BLANK] to the cached server.", a: "suffix" },
        { q: "For high-performance computing, [BLANK] communication assigns each process a unique id known to all other group processes.", a: "direct" },
        { q: "The function send(ALL, m) transmits message m to [BLANK] processes within the group.", a: "all" },
        { q: "An integer assigned to a process by the OS for communication is called a [BLANK].", a: "port" },
        { q: "A communication point of the form (IP, p) that uniquely identifies any process in a network is called a [BLANK].", a: "socket" },
        { q: "Ports support [BLANK] communication — many senders, but only one receiver.", a: "many-to-one" },
        { q: "Mailboxes support [BLANK] communication because multiple senders and receivers can access the same mailbox.", a: "many-to-many" },
        { q: "A data structure maintained by the OS into which messages can be placed and retrieved is called a [BLANK].", a: "mailbox" },
        { q: "A [BLANK] send resumes the sender as soon as the message is copied into the sender's OS buffer.", a: "non-blocking" },
        { q: "A [BLANK] send blocks the sending process until the message has been fully delivered to the receiver.", a: "blocking" },
        { q: "A [BLANK] receive blocks the receiving process until a message has been copied into the receiver's buffer.", a: "blocking" },
        { q: "Communication is [BLANK] if both sender and receiver must be active at the same time to exchange a message.", a: "synchronous" },
        { q: "A blocking send combined with a blocking receive results in [BLANK] communication.", a: "synchronous" },
        { q: "A [BLANK] hides message-passing details by providing a construct similar to a regular function call.", a: "remote procedure call" },
        { q: "The process of packing and unpacking parameters for transmission between computers is called [BLANK].", a: "marshaling" },
        { q: "A [BLANK] stub is a local library function representing the remote function on the client side.", a: "client" },
        { q: "A [BLANK] stub is the server-side counterpart responsible for invoking the named function.", a: "server" },
        { q: "A local process called a [BLANK] maintains a table of server names and associated port numbers.", a: "binder" },
        { q: "When a server's IP is unknown, a [BLANK] server at an agreed-upon location maintains a table of server names and IP addresses.", a: "directory" },
        { q: "Pointers cannot be passed directly in an RPC because they are only valid within a single computer's [BLANK].", a: "address space" },
        { q: "[BLANK] DSM supports sharing of specific designated portions of address spaces via library routines.", a: "structured" },
        { q: "[BLANK] DSM unites multiple page-based address spaces into one large uniform space via the OS.", a: "unstructured" },
        { q: "When two unrelated variables accessed by different computers end up on the same page, it's called [BLANK].", a: "false sharing" },
        { q: "False sharing is analogous to [BLANK] in virtual memory.", a: "thrashing" },
        { q: "In DSM, larger page sizes reduce transfer startup cost but increase the risk of [BLANK].", a: "false sharing" },
        { q: "In the write-[BLANK] protocol, when a page is modified, all remote replicas are invalidated.", a: "invalidate" },
        { q: "In the write-[BLANK] protocol, when a page is modified, the new value is propagated to all replicas.", a: "update" },
        { q: "Unlike virtual memory, unstructured DSM distributes pages over the [BLANK] of multiple computers.", a: "memories" },
        { q: "In R migrate / W migrate DSM, concurrent accesses cause the page to move [BLANK] between computers.", a: "repeatedly" },
        { q: "A DSM obeys [BLANK] consistency if reading variable x always returns the most recently written value.", a: "strict" },
        { q: "The [BLANK] relation specifies when two events are causally related.", a: "happened-before" },
        { q: "Two events are said to be [BLANK] if neither causally influenced the other.", a: "concurrent" },
        { q: "[BLANK] clocks are a time-stamping mechanism that guarantees preservation of the happened-before relationship.", a: "logical" },
        { q: "A [BLANK] is a virtual entity whose possession entitles a process to enter the critical section.", a: "token" },
        { q: "In the centralized token approach, the main drawback is that the [BLANK] becomes a bottleneck.", a: "coordinator" },
        { q: "In the token ring approach, all processes must participate in [BLANK] even when not entering the CS.", a: "passing the token" },
        { q: "The loss of a token requires an [BLANK] algorithm to decide which process generates a new one.", a: "election" },
        { q: "In distributed mutual exclusion, process p enters the CS after receiving [BLANK] from all others.", a: "permission" },
        { q: "In the [BLANK] deadlock prevention strategy, an older process waits while a younger process restarts.", a: "wait-die" },
        { q: "In the [BLANK] deadlock prevention strategy, an older process rolls back the younger.", a: "wound-wait" },
        { q: "The main drawback of wound-wait is that some actions such as [BLANK] cannot be rolled back.", a: "printing a document" },
        { q: "The [BLANK] algorithm detects distributed deadlock by sending a probe along request edges of the wait-for graph looking for a cycle back to the initiator.", a: "edge-chasing" },
        { q: "When file location is hidden so users use the same path name regardless of host, this is location [BLANK].", a: "transparency" },
        { q: "Making a remote directory subtree accessible under a local path name is called [BLANK].", a: "mounting" },
        { q: "[BLANK] file semantics require that a write is immediately visible to all sharing clients.", a: "unix" },
        { q: "Under [BLANK] semantics, a write is not visible until the writing client closes the file.", a: "session" },
        { q: "Under [BLANK] file semantics, a shared file cannot be modified; a write creates a new version.", a: "immutable" },
        { q: "[BLANK] caching means the server maintains a memory cache for recently accessed files.", a: "server" },
        { q: "[BLANK] caching means each client maintains a separate cache in local memory.", a: "client" },
        { q: "Client caching is incompatible with [BLANK] semantics because updates aren't immediately visible.", a: "unix" },
        { q: "In the Read-Any/Write-All protocol, a client may read [BLANK] replica.", a: "any" },
        { q: "In the Read-Any/Write-All protocol, a client must update [BLANK] replicas.", a: "all" },
        { q: "In the Primary/Backup protocol, a client may update [BLANK] replica.", a: "one" },
        { q: "A [BLANK] server maintains the open file status for all clients in an Open File Table.", a: "stateful" },
        { q: "A [BLANK] server maintains no information about open files — every request is self-contained.", a: "stateless" },
        { q: "Between capability lists and access control lists, [BLANK] lists make revoking a right harder because permissions for a given object are scattered across many process lists rather than stored centrally.", a: "capability" },
    ]
};

// ─── Synonyms / Accepted Alternatives ────────────────────────────────────────

const synonymsMap = {
    // Chapter 1
    '1|shell': ['shell', 'command line', 'command interpreter', 'cli'],
    '1|privileged instruction': ['privileged instruction', 'privileged instructions'],
    '1|doubles': ['doubles', 'roughly doubles', 'approximately doubles'],
    '1|user, system call, OS, user': ['user, system call, OS, user', 'user, system call, kernel, user'],
    '1|abstraction': ['abstraction'],
    '1|user, kernel': ['user, kernel', 'user mode, kernel mode'],
    '1|can, cannot': ['can, cannot'],
    '1|privileged instructions': ['privileged instructions', 'privileged instruction'],
    '1|multiprogramming': ['multiprogramming', 'multi-programming'],
    '1|time-sharing': ['time-sharing', 'time sharing', 'timesharing'],
    '1|resource manager': ['resource manager'],
    '1|system call': ['system call', 'system calls'],
    '1|timer': ['timer', 'hardware timer', 'clock interrupt'],
    '1|interrupt, trap': ['interrupt, trap'],
    '1|trap, interrupt': ['trap, interrupt', 'system call, interrupt'],
    '1|user, system calls': ['user, system calls', 'user mode, system calls'],
    '1|monopolize': ['monopolize', 'starve', 'hog', 'run forever'],
    '1|extended machine, resource manager, security': ['extended machine, resource manager, security'],
    '1|trap': ['trap', 'software trap', 'software interrupt'],
    '1|user': ['user', 'user mode'],
    '1|extended': ['extended'],
    '1|virtualization': ['virtualization'],
    '1|210': ['210'],
    '1|180': ['180'],
    '1|150': ['150'],
    '1|process': ['process', 'program'],
    '1|mainframe, server': ['mainframe, server'],

    // Chapter 2
    '2|memory, stack': ['memory, stack', 'address space, stack', 'code and heap, stack'],
    '2|context switch': ['context switch'],
    '2|idle time': ['idle time', 'wasted time', 'cpu idle time'],
    '2|running': ['running', 'executing'],
    '2|Thread Control Block': ['Thread Control Block', 'TCB'],
    '2|new, ready, running, blocked, suspended-ready, suspended-blocked': ['new, ready, running, blocked, suspended-ready, suspended-blocked'],
    '2|ready': ['ready'],
    '2|zombie': ['zombie', 'zombie process'],
    '2|an event, swapped out': ['an event, swapped out', 'a resource, swapped out'],
    '2|Process Control Block': ['Process Control Block', 'PCB'],
    '2|Resource Control Block': ['Resource Control Block', 'RCB'],
    '2|running, ready, blocked': ['running, ready, blocked', 'ready, running, blocked'],
    '2|timer': ['timer', 'timer interrupt', 'hardware timer', 'clock interrupt'],
    '2|resource': ['resource'],
    '2|thread': ['thread', 'threads'],

    // Chapter 3
    '3|ready': ['ready'],
    '3|long-term, short-term': ['long-term, short-term', 'admission, cpu scheduling'],
    '3|preemptive': ['preemptive'],
    '3|SJF': ['sjf', 'shortest job first', 'shortest job next'],
    '3|Round Robin': ['round robin', 'rr'],
    '3|response': ['response', 'response time'],
    '3|starvation': ['starvation'],
    '3|completion time, arrival time': ['completion time, arrival time', 'finish time, arrival time'],
    '3|length': ['length', 'duration', 'burst length'],
    '3|SRT': ['srt', 'shortest remaining time', 'shortest remaining time first', 'srtf'],
    '3|FIFO': ['fifo', 'first come first served', 'fcfs', 'first in first out'],
    '3|3.67': ['3.67', '11/3', '3.7'],
    '3|5.33': ['5.33', '16/3', '5.3'],
    '3|10.5': ['10.5'],
    '3|I/O': ['i/o', 'io', 'i/o bound'],
    '3|blocks': ['blocks', 'yields', 'blocks itself', 'gives up the cpu'],
    '3|different': ['different', 'different scheduling', 'different requirements'],

    // Chapter 4
    '4|mutual exclusion, progress, bounded waiting, performance': ['mutual exclusion, progress, bounded waiting, performance'],
    '4|semaphore': ['semaphore'],
    '4|small': ['small'],
    '4|1': ['1', 'one'],
    '4|monitor': ['monitor'],
    '4|10': ['10', 'ten'],
    '4|wait, signal': ['wait, signal'],
    '4|race': ['race', 'race condition'],
    '4|waits': ['waits', 'blocks', 'sleeps'],
    '4|decrements, blocked': ['decrements, blocked', 'decrements s, blocks'],
    '4|non-negative': ['non-negative', 'nonnegative', 'non negative'],
    '4|empty': ['empty'],
    '4|tick': ['tick'],
    '4|2': ['2', '1'],
    '4|concurrent, cooperating': ['concurrent, cooperating'],
    '4|V': ['v', 'V(s)', 'v(s)', 'signal'],
    '4|empty, mutex': ['empty, mutex', 'empty slot, mutex', 'empty space, mutex', 'empty slot and mutex'],

    // Chapter 5
    '5|tick': ['tick'],
    '5|request, blocked': ['request, blocked'],
    '5|reusable, consumable': ['reusable, consumable'],
    '5|denied': ['denied', 'rejected', 'refused'],
    '5|maximum claim, current allocation': ['maximum claim, current allocation', 'max claim, allocated'],
    '5|circular wait, no preemption': ['circular wait, no preemption', 'no preemption, circular wait'],
    '5|loans, credit': ['loans, credit'],
    '5|circles, squares': ['circles, squares'],
    '5|assignment, request': ['assignment, request', 'hold, request'],
    '5|reducible': ['reducible', 'completely reducible'],
    '5|blocked': ['blocked', 'waiting'],
    '5|cycle': ['cycle'],
    '5|p2, p3, p4': ['p2, p3, p4', 'p2, p4, p3', 'p3, p2, p4', 'p3, p4, p2', 'p4, p2, p3', 'p4, p3, p2'],

    // Chapter 6
    '6|relocated': ['relocated', 'moved'],
    '6|first fit, next fit': ['first fit, next fit'],
    '6|best fit, worst fit': ['best fit, worst fit'],
    '6|page, offset': ['page, offset', 'page number, offset'],
    '6|logical': ['logical', 'virtual'],
    '6|0': ['0', 'zero'],
    '6|segment, segment': ['segment, segment', 'segment, segment table'],
    '6|temporal': ['temporal', 'locality', 'principle of locality'],
    '6|external': ['external', 'external fragmentation'],
    '6|page, frame, page table': ['page, frame, page table'],
    '6|external, internal': ['external, internal'],
    '6|translation lookaside buffer': ['translation lookaside buffer', 'TLB'],
    '6|static, dynamic': ['static, dynamic'],
    '6|3': ['3', 'three'],
    '6|base': ['base', 'base register', 'relocation register'],
    '6|dynamic, static': ['dynamic, static'],
    '6|coalescing': ['coalescing', 'merging', 'hole merging'],
    '6|word': ['word', 'memory word', 'machine word'],

    // Chapter 7
    '7|0': ['0', 'zero'],
    '7|concurrently': ['concurrently', 'concurrent', 'at the same time'],
    '7|1, 0': ['1, 0', '1,0', '1 and 0'],
    '7|reference string': ['reference string', 'ref string', 'reference sequence'],
    '7|clock interval': ['clock interval', 'tick', 'clock tick'],
    '7|optimal': ['optimal', 'OPT', 'optimal algorithm', 'belady optimal'],
    '7|LRU': ['lru', 'least recently used', 'least-recently-used'],
    '7|service time': ['service time', 'service-time'],
    '7|directory': ['directory', 'page directory'],
    '7|outside': ['outside', 'not in', 'outside of'],
    '7|future references': ['future references', 'future accesses'],
    '7|needed': ['needed', 'when needed', 'on demand'],
    '7|page directory': ['page directory', 'directory'],
    '7|d': ['d'],
    '7|update page table': ['update page table', 'update the page table'],
    '7|base': ['base', 'base register', 'relocation', 'relocation register'],
    '7|FIFO': ['fifo', 'first in first out', 'first-in-first-out'],
    '7|between page faults': ['between page faults'],
    '7|aging register': ['aging register', 'aging register value'],
    '7|written': ['written', 'written to disk', 'write back', 'written back'],
    '7|decrease': ['decrease', 'reduce'],
    '7|increases': ['increases', 'grows'],
    '7|time': ['time', 'interval'],
    '7|modified': ['modified', 'dirty', 'modified bit'],
    '7|memory and disk': ['memory and disk', 'disk and memory'],
    '7|page fault': ['page fault', 'page-fault'],
    '7|working set': ['working set'],
    '7|grows': ['grows', 'increases'],
    '7|smallest': ['smallest', 'lowest'],
    '7|(1-P)*m + P*S': ['(1-P)*m + P*S', '(1 - P) * m + P * S'],
    '7|page fault rate': ['page fault rate', 'P', 'fault rate'],
    '7|clean': ['clean', 'not modified', 'unmodified'],

    // Chapter 8
    '8|open file table': ['open file table', 'OFT'],
    '8|file control block': ['file control block', 'FCB', 'i-node', 'inode'],
    '8|relative path': ['relative path', 'relative pathname'],
    '8|bitmap, free, allocated': ['bitmap', 'bit map', 'free', 'allocated'],
    '8|record': ['record'],
    '8|link count': ['link count', 'reference count'],
    '8|magic number': ['magic number', 'file signature'],
    '8|..': ['..'],
    '8|file system': ['file system', 'filesystem'],
    '8|k/b, k mod b': ['k/b', 'k mod b', 'k % b'],
    '8|removed': ['removed', 'deleted', 'evicted'],
    '8|AND': ['AND', 'bitwise AND', '&'],
    '8|single indirect block': ['single indirect block', 'single indirect'],
    '8|sequential access': ['sequential access', 'sequential'],
    '8|read/write buffer': ['read/write buffer', 'buffer'],
    '8|file length': ['file length', 'length'],
    '8|absolute path name': ['absolute path name', 'absolute pathname', 'absolute path'],
    '8|linked': ['linked', 'linked allocation', 'linked-list allocation'],
    '8|file': ['file'],
    '8|index': ['index', 'file descriptor', 'fd'],
    '8|File Allocation Table': ['File Allocation Table', 'FAT'],
    '8|FCB': ['FCB', 'file control block'],
    '8|Metadata': ['metadata', 'file metadata', 'header info'],
    '8|contiguous': ['contiguous', 'contiguous allocation'],
    '8|OR': ['OR', 'bitwise OR', '|'],
    '8|symbolic link': ['symbolic link', 'symlink', 'soft link'],
    '8|indexed': ['indexed', 'indexed allocation'],

    // Chapter 9
    '9|linked': ['linked', 'linked allocation'],
    '9|device controller': ['device controller', 'controller'],
    '9|SSTF': ['sstf', 'shortest seek time first'],
    '9|SCAN': ['scan', 'elevator algorithm'],
    '9|buffer': ['buffer', 'cache'],
    '9|programmed i/o': ['programmed i/o', 'programmed I/O', 'programmed input/output'],
    '9|C-SCAN': ['c-scan', 'cscan'],
    '9|fairer': ['fairer', 'more fair'],
    '9|buffer cache': ['buffer cache', 'disk cache'],
    '9|sector': ['sector', 'sector forwarding'],
    '9|cooked': ['cooked', 'canonical mode'],
    '9|distributed': ['distributed parity', 'distributed'],
    '9|DMA': ['dma', 'direct memory access'],
    '9|error-correcting code': ['error-correcting code', 'ECC'],
    '9|summing': ['summing', 'parity-sum'],
    '9|tracks': ['tracks'],
    '9|blocks': ['blocks'],
    '9|command': ['command register', 'command'],
    '9|Hamming': ['hamming'],
    '9|polling': ['polling'],
    '9|sustained': ['sustained'],
    '9|starvation': ['starvation'],
    '9|0': ['0', 'zero'],
    '9|device driver': ['device driver', 'driver'],
    '9|1': ['1', 'one'],
    '9|striping': ['striping'],
    '9|status': ['status', 'status register'],
    '9|busy': ['busy', 'busy register', 'status flag'],
    '9|average': ['average', 'average transfer rate', 'average data rate'],
    '9|storage': ['storage', 'stable storage'],
    '9|interface': ['interface', 'standard interface', 'i/o interface'],
    '9|seek': ['seek', 'seek time'],

    // Chapter 10
    '10|slipping': ['slipping'],
    '10|condition': ['condition', 'trigger condition'],
    '10|virus': ['virus'],
    '10|replay': ['replay'],
    '10|biometrics': ['biometrics'],
    '10|secret key': ['secret key', 'symmetric key', 'symmetric cryptography'],
    '10|zero-knowledge': ['zero-knowledge'],
    '10|factoring': ['factoring'],
    '10|outside': ['outside'],
    '10|logic bomb': ['logic bomb'],
    '10|back door': ['back door', 'backdoor', 'trapdoor'],
    '10|worm': ['worm'],
    '10|leakage': ['leakage', 'information leakage'],
    '10|imposter': ['imposter', 'impostor'],
    '10|authentication': ['authentication'],
    '10|threshold': ['threshold'],
    '10|capability list': ['capability list'],
    '10|length': ['length', 'input length'],
    '10|access control list': ['access control list', 'ACL'],
    '10|revoking': ['revoking', 'revocation'],
    '10|copy': ['copy'],
    '10|phishing': ['phishing'],
    '10|buffer overflow': ['buffer overflow', 'stack overflow'],
    '10|one-way hash function': ['one-way hash function', 'hash function', 'one-way hash', 'cryptographic hash'],
    '10|insert': ['insert', 'attach', 'inject', 'embed'],
    '10|signature': ['signature', 'signature-based'],
    '10|trojan horse': ['trojan horse', 'trojan', 'trojan program'],
    '10|stable': ['stable', 'stable storage'],

    // Chapter 11
    '11|distributed system': ['distributed system'],
    '11|hosts': ['hosts'],
    '11|messages': ['messages'],
    '11|IP address': ['ip address', 'ip'],
    '11|local area': ['local area', 'lan'],
    '11|wide area': ['wide area', 'wan'],
    '11|distributed shared memory': ['distributed shared memory', 'DSM'],
    '11|distributed file system': ['distributed file system'],
    '11|name resolution': ['name resolution'],
    '11|DNS': ['dns'],
    '11|domain': ['domain'],
    '11|top-level domains': ['top-level domains', 'TLDs'],
    '11|name server': ['name server'],
    '11|resolver': ['resolver'],
    '11|iterative': ['iterative'],
    '11|recursive': ['recursive'],
    '11|cache': ['cache'],
    '11|suffix': ['suffix'],
    '11|id': ['id'],
    '11|all': ['all'],
    '11|port': ['port'],
    '11|socket': ['socket'],
    '11|many-to-one': ['many-to-one', 'm-to-1', 'many to one'],
    '11|many-to-many': ['many-to-many'],
    '11|mailbox': ['mailbox'],
    '11|non-blocking': ['non-blocking', 'nonblocking', 'non blocking'],
    '11|blocking': ['blocking'],
    '11|synchronous': ['synchronous'],
    '11|remote procedure call': ['remote procedure call', 'rpc'],
    '11|marshaling': ['marshaling', 'marshalling'],
    '11|client': ['client'],
    '11|server': ['server'],
    '11|binder': ['binder'],
    '11|address space': ['address space'],
    '11|structured': ['structured', 'structured DSM'],
    '11|unstructured': ['unstructured', 'unstructured DSM'],
    '11|false sharing': ['false sharing'],
    '11|thrashing': ['thrashing'],
    '11|invalidate': ['invalidate', 'write-invalidate'],
    '11|update': ['update', 'write-update'],
    '11|memories': ['memories', 'main memories', 'local memories'],
    '11|repeatedly': ['repeatedly', 'back and forth'],
    '11|strict': ['strict', 'strict consistency'],
    '11|happened-before': ['happened-before'],
    '11|concurrent': ['concurrent'],
    '11|logical': ['logical', 'logical clocks'],
    '11|token': ['token'],
    '11|coordinator': ['coordinator', 'controller'],
    '11|passing the token': ['passing the token', 'token circulation'],
    '11|election': ['election'],
    '11|permission': ['permission', 'OK'],
    '11|wait-die': ['wait-die', 'wait die'],
    '11|wound-wait': ['wound-wait', 'wound wait'],
    '11|printing a document': ['printing a document', 'i/o', 'io operations', 'printing'],
    '11|edge-chasing': ['edge-chasing', 'probe', 'edge chasing'],
    '11|transparency': ['transparency', 'location transparency'],
    '11|mounting': ['mounting', 'mount'],
    '11|unix': ['unix', 'UNIX'],
    '11|session': ['session', 'session semantics'],
    '11|immutable': ['immutable', 'immutable file'],
    '11|server caching': ['server caching'],
    '11|client caching': ['client caching'],
    '11|any': ['any', 'any replica'],
    '11|one': ['one', 'only the primary', 'the primary'],
    '11|stateful': ['stateful'],
    '11|stateless': ['stateless'],
    '11|direct': ['direct', 'direct communication'],
    '11|directory': ['directory', 'directory server'],
    '11|capability': ['capability', 'capability lists'],
};

// ─── Merge synonyms into database entries ────────────────────────────────────

function mergeSynonymsIntoDatabase() {
    for (const chap in database) {
        database[chap].forEach(item => {
            const key = chap + '|' + (item.a || '').toString();
            if (synonymsMap[key]) {
                item.synonyms = synonymsMap[key];
            }
        });
    }
}
